/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Groups: typeof import('./src/components/AppDrawers/Groups.vue')['default']
    Sources: typeof import('./src/components/AppDrawers/Sources.vue')['default']
    VideoPlayer: typeof import('./src/components/AppDrawers/VideoPlayer.vue')['default']
    M3uParser: typeof import('./src/components/M3uParser.vue')['default']
    XmltvParser: typeof import('./src/components/XmltvParser.vue')['default']
  }
}
