/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddM3uFile: typeof import('./src/components/AddM3uFile.vue')['default']
    AppDrawerGroups: typeof import('./src/components/AppDrawers/AppDrawerGroups.vue')['default']
    AppDrawerSources: typeof import('./src/components/AppDrawers/AppDrawerSources.vue')['default']
    AppDrawerVideo: typeof import('./src/components/AppDrawers/AppDrawerVideo.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Groups: typeof import('./src/components/AppDrawers/Groups.vue')['default']
    M3uGroups: typeof import('./src/components/M3uGroups.vue')['default']
    M3uParser: typeof import('./src/components/M3uParser.vue')['default']
    M3uSearch: typeof import('./src/components/M3uSearch.vue')['default']
    M3uStreams: typeof import('./src/components/M3uStreams.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Sources: typeof import('./src/components/AppDrawers/Sources.vue')['default']
    StreamSearch: typeof import('./src/components/StreamSearch.vue')['default']
    VideoPlayer: typeof import('./src/components/AppDrawers/VideoPlayer.vue')['default']
    XmltvParser: typeof import('./src/components/XmltvParser.vue')['default']
  }
}
